---
abstract: 'read a sheet from Excel file into a simple arrayref of arrayrefs'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-DataFromExcel
provides:
  Spreadsheet::DataFromExcel:
    file: lib/Spreadsheet/DataFromExcel.pm
    version: 0.0102
requires:
  Spreadsheet::ParseExcel: 0.49
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0102
